version: '3.8'

services:
  app:
    image: vite-app:latest
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
    # deploy:
    #   placement:
    #     constraints:
    #       - 'node.role==worker'
# networks:
#   default:
#     name: portfolio_network
#     external: true
